import streamlit as st

st.header("SYMPOSIUM REGISTRATION")
st.write("DHANALAKSHMI SRINIVASAN COLLEGE OF ENGINEERING AND TECHNOLOGY . MAMALLAPURAM CHENNAI-603104")
st.divider()
st.write("Recorded as aaaa.aaaa@gmail.com") 
st.write("The name, email address and photo associated with your Google Account will be recorded when you upload files and submit this form")
st.write("Email")
st.text_input("Enter your mail * ")
st.divider()
st.write("ONLINE REGISTRATION DEAD LINE :")        
st.write("TITLE")
st.write("* Registration Fees : Rs.200(for Technical & Non-Technical)")
st.write("* Registration Fees  Each game Rs.50. It is only availability on offline")
st.write("* Food and transport provide by organizing team")
st.write("* COLLEGE ID CARD is Mandatory")
st.divider()
st.text_input("NAME * ")
st.text_input("Phone number * ")
st.text_input("Email * ")
st.radio("Year * ",[":rainbow[1st year]", "2nd year", "3rd year","4th year"])
st.text_input("Department * ")
st.title("Technical events")
st.checkbox("Paper Presentation")
st.checkbox("Coding")
st.checkbox("Debugging")
st.checkbox("Technical quiz")
st.title("Non-technical events")
st.checkbox("Dance")
st.checkbox("Singing")
st.checkbox("Treasure hunt")
st.checkbox("Short Film")

st.text_input("Team name * ")
st.text_input("Participant 1 * ")
st.text_input("Participant 2")
st.button("Submit")